name: "vcpkg-cache"
description: ""
inputs:
  token:
    description: "GitHub workflow token"
    required: true
  action:
    description: "Action to perform ('restore' or 'save')"
    required: true
  archive-path:
    description: "Path to the vcpkg archives relative to $GITHUB_WORKSPACE"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_TOKEN: ${{ inputs.token }}
    INPUT_ACTION: ${{ inputs.action }}
    INPUT_ARCHIVE_PATH: ${{ inputs.archive-path }}
