name: "vcpkg-cache"
description: "Caches filesystem vcpkg archives using actions/cache"
branding:
  icon: "archive"
  color: "yellow"
inputs:
  token:
    description: "GitHub workflow token"
    required: true
  archive-path:
    description: "Path to the vcpkg archives relative to $GITHUB_WORKSPACE"
    required: true
runs:
  using: "node20"
  main: "src/restore.js"
  post: "src/save.js"
