name: "vcpkg-cache"
description: "Caches filesystem vcpkg archives using actions/cache"
branding:
  icon: "archive"
  color: "yellow"
inputs:
  token:
    description: "GitHub workflow token"
    required: true
  prefix:
    description: "Prefix added to all cache keys. Can be used for e.g. independently restoring cache entries for each vcpkg triplet."
    required: false
    default: "vcpkg/"
outputs:
  path:
    description: "Absolute path to the written cache"
runs:
  using: "node20"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
