name: "vcpkg-cache"
description: ""
inputs:
  token:
    description: "GitHub workflow token"
    required: true
  action:
    description: "Action to perform ('restore' or 'save')"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_TOKEN: ${{ inputs.token }}
    INPUT_ACTION: ${{ inputs.action }}
