name: "vcpkg-cache"
description: "Caches filesystem vcpkg archives using actions/cache"
branding:
  icon: "archive"
  color: "yellow"
inputs:
  token:
    description: "GitHub workflow token"
    required: true
outputs:
  path:
    description: "Absolute path to the written cache"
runs:
  using: "node20"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
