name: "vcpkg-cache"
description: "Caches filesystem vcpkg archives using actions/cache"
branding:
  icon: "archive"
  color: "yellow"
inputs:
  token:
    description: "GitHub workflow token"
    required: true
  action:
    description: "Action to perform ('restore' or 'save')"
    required: true
  archive-path:
    description: "Path to the vcpkg archives relative to $GITHUB_WORKSPACE"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/taservers/vcpkg-cache:master"
  entrypoint: "./restore.sh"
  post-entrypoint: "./save.sh"
  env:
    INPUT_TOKEN: ${{ inputs.token }}
    INPUT_ARCHIVE_PATH: ${{ inputs.archive-path }}
