name: Push Feature

on:
  pull_request:

jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yaml
    # Only run on forks to avoid duplicating the "push" workflow
    if: ${{ github.event.pull_request.head.repo.fork }}

  integration-test:
    uses: ./.github/workflows/integration-test.yaml
    # Only run on forks to avoid duplicating the "push" workflow
    if: ${{ github.event.pull_request.head.repo.fork }}
