name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Parse CHANGELOG.md
        uses: mindsers/changelog-reader-action@v2
        id: changelog
        with:
          validation_level: warn

      - name: Determine major version
        uses: actions/github-script@v5
        id: major-version
        with:
          script: |
            const version = "${{ steps.changelog.outputs.version }}";
            return version.split(".")[0];
          result-encoding: "string"

      - name: Push granular release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.changelog.outputs.version }}"
          name: "v${{ steps.changelog.outputs.version }}"
          body: ${{ steps.changelog.outputs.changes }}

      - name: Push major version release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.major-version.outputs.result }}"
          name: "v${{ steps.major-version.outputs.result }}"
          body: ${{ steps.changelog.outputs.changes }}
